<Project Sdk="Dalamud.NET.Sdk/12.0.2">

	<PropertyGroup>
		<Authors>electr0sheep, Nuko, Lother</Authors>
		<Description>Dalamud plugin for item vendors</Description>
		<Version>7.15.0.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CheapLoc" Version="1.1.8" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
